### ISSUE TITLE
Access to Dataset

### ISSUE THREAD

**Issue by Tasmin153** [WENGSYX/GlobalSpan#2]
Hi there,

Thanks for sharing the great work. I emailed for access to the dataset a few weeks back, could you please check? It would be great to get the dataset and reproduce the results.

**Comment by WENGSYX** [comment]
Thank you for your interest in our work. I'm glad to hear that you found our paper useful. Since we do not have the copyright, we can only provide the original official dataset links and cannot distribute the processed data. You can download the MedVidQA train/valid/test datasets from https://osf.io/pc594/files/osfstorage. Additionally, you'll need to download the video features from https://bionlp.nlm.nih.gov/VideoFeatures.zip.

In addition, we also provide CMIVQA task which is a Chinese version dataset of the MedVidQA task -> https://github.com/WENGSYX/CMIVQA_Baseline/tree/main/task1

In this repository, we provide the complete training data required for running CCGS training.

Best regards,

Yixuan Weng
